/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_Admin (void);
GtkWidget* create_Paiment (void);
GtkWidget* create_kine (void);
GtkWidget* create_Coach (void);
GtkWidget* create_Dector (void);
GtkWidget* create_User (void);
